# Form implementation generated from reading ui file 'design/dotui/login_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        Form.setMinimumSize(QtCore.QSize(400, 600))
        Form.setMaximumSize(QtCore.QSize(400, 600))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        Form.setFont(font)
        Form.setStyleSheet("background-color:rgb(15, 23, 42)")
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, -31, 400, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.userLogin = QtWidgets.QWidget()
        self.userLogin.setObjectName("userLogin")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.userLogin)
        self.passwordLineEdit.setGeometry(QtCore.QRect(88, 311, 251, 41))
        self.passwordLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #1e293b;   /* زمینه تیره */\n"
"    color: #e2e8f0;              /* متن روشن */\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"\n"
"    /* خط و عمق */\n"
"    border: 2px solid #0f172a;\n"
"    border-bottom: 4px solid #0a0f1c;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3b82f6;   /* آبی روشن */\n"
"    border-bottom: 4px solid #2563eb;\n"
"    outline: none;\n"
"}\n"
"")
        self.passwordLineEdit.setMaxLength(100)
        self.passwordLineEdit.setFrame(True)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setCursorPosition(0)
        self.passwordLineEdit.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.passwordLineEdit.setClearButtonEnabled(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.headerText = QtWidgets.QLabel(parent=self.userLogin)
        self.headerText.setGeometry(QtCore.QRect(-10, 80, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(36)
        self.headerText.setFont(font)
        self.headerText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.headerText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerText.setObjectName("headerText")
        self.keyIcon = QtWidgets.QLabel(parent=self.userLogin)
        self.keyIcon.setGeometry(QtCore.QRect(50, 316, 30, 30))
        self.keyIcon.setText("")
        self.keyIcon.setPixmap(QtGui.QPixmap(":/icons/icons/key.png"))
        self.keyIcon.setScaledContents(True)
        self.keyIcon.setObjectName("keyIcon")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.userLogin)
        self.usernameLineEdit.setGeometry(QtCore.QRect(88, 234, 251, 41))
        self.usernameLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #1e293b;   /* زمینه تیره */\n"
"    color: #e2e8f0;              /* متن روشن */\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"\n"
"    /* خط و عمق */\n"
"    border: 2px solid #0f172a;\n"
"    border-bottom: 4px solid #0a0f1c;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3b82f6;   /* آبی روشن */\n"
"    border-bottom: 4px solid #2563eb;\n"
"    outline: none;\n"
"}\n"
"")
        self.usernameLineEdit.setMaxLength(100)
        self.usernameLineEdit.setFrame(True)
        self.usernameLineEdit.setCursorPosition(0)
        self.usernameLineEdit.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.usernameLineEdit.setClearButtonEnabled(True)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.pTextLogin = QtWidgets.QLabel(parent=self.userLogin)
        self.pTextLogin.setGeometry(QtCore.QRect(-10, 140, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.pTextLogin.setFont(font)
        self.pTextLogin.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.pTextLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pTextLogin.setObjectName("pTextLogin")
        self.userIcon = QtWidgets.QLabel(parent=self.userLogin)
        self.userIcon.setGeometry(QtCore.QRect(48, 240, 32, 32))
        self.userIcon.setText("")
        self.userIcon.setPixmap(QtGui.QPixmap(":/icons/icons/user_for_login.png"))
        self.userIcon.setScaledContents(True)
        self.userIcon.setObjectName("userIcon")
        self.loginButton = QtWidgets.QPushButton(parent=self.userLogin)
        self.loginButton.setGeometry(QtCore.QRect(128, 410, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(16)
        font.setBold(True)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("#loginButton {\n"
"    background-color: #1e293b;        /* خاکستری-آبی تیره، ست با پس‌زمینه */\n"
"    color: #e2e8f0;                   /* متن روشن (خاکستری خیلی روشن) */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    font-weight: bold;\n"
"\n"
"    /* عمق (سایه‌ی مصنوعی) */\n"
"    border: 2px solid #0f172a;        /* خط دور تیره‌تر */\n"
"    border-bottom: 4px solid #0a0f1c; /* سایه پایین برای برجسته شدن */\n"
"\n"
"    /*transition: all 0.2s;*/\n"
"}\n"
"\n"
"#loginButton:hover {\n"
"    background-color: #334155;        /* کمی روشن‌تر وقتی موس میره روش */\n"
"    color: white;\n"
"}\n"
"\n"
"#loginButton:pressed {\n"
"    background-color: #1e293b;\n"
"    border: 2px solid #0a0f1c;\n"
"    border-top: 4px solid #0a0f1c;    /* وقتی فشار میدی انگار دکمه فرو میره */\n"
"    padding-top: 12px;                /* حرکت جزئی برای طبیعی‌تر شدن */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.dontHaveAccountText = QtWidgets.QLabel(parent=self.userLogin)
        self.dontHaveAccountText.setGeometry(QtCore.QRect(78, 500, 131, 41))
        self.dontHaveAccountText.setStyleSheet("color:white;")
        self.dontHaveAccountText.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dontHaveAccountText.setObjectName("dontHaveAccountText")
        self.registerLinkText = QtWidgets.QLabel(parent=self.userLogin)
        self.registerLinkText.setGeometry(QtCore.QRect(210, 500, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.registerLinkText.setFont(font)
        self.registerLinkText.setStyleSheet("color:white;")
        self.registerLinkText.setObjectName("registerLinkText")
        self.tabWidget.addTab(self.userLogin, "")
        self.userRegister = QtWidgets.QWidget()
        self.userRegister.setObjectName("userRegister")
        self.submitButton = QtWidgets.QPushButton(parent=self.userRegister)
        self.submitButton.setGeometry(QtCore.QRect(128, 450, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(16)
        font.setBold(True)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet("#submitButton {\n"
"    background-color: #1e293b;        /* خاکستری-آبی تیره، ست با پس‌زمینه */\n"
"    color: #e2e8f0;                   /* متن روشن (خاکستری خیلی روشن) */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    font-weight: bold;\n"
"\n"
"    /* عمق (سایه‌ی مصنوعی) */\n"
"    border: 2px solid #0f172a;        /* خط دور تیره‌تر */\n"
"    border-bottom: 4px solid #0a0f1c; /* سایه پایین برای برجسته شدن */\n"
"\n"
"    /*transition: all 0.2s;*/\n"
"}\n"
"\n"
"#submitButton:hover {\n"
"    background-color: #334155;        /* کمی روشن‌تر وقتی موس میره روش */\n"
"    color: white;\n"
"}\n"
"\n"
"#submitButton:pressed {\n"
"    background-color: #1e293b;\n"
"    border: 2px solid #0a0f1c;\n"
"    border-top: 4px solid #0a0f1c;    /* وقتی فشار میدی انگار دکمه فرو میره */\n"
"    padding-top: 12px;                /* حرکت جزئی برای طبیعی‌تر شدن */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.submitButton.setObjectName("submitButton")
        self.pTextRegister = QtWidgets.QLabel(parent=self.userRegister)
        self.pTextRegister.setGeometry(QtCore.QRect(-10, 140, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.pTextRegister.setFont(font)
        self.pTextRegister.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.pTextRegister.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pTextRegister.setObjectName("pTextRegister")
        self.loginLinkText = QtWidgets.QLabel(parent=self.userRegister)
        self.loginLinkText.setGeometry(QtCore.QRect(243, 527, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.loginLinkText.setFont(font)
        self.loginLinkText.setStyleSheet("color:white;")
        self.loginLinkText.setObjectName("loginLinkText")
        self.alreadyHaveAccountText = QtWidgets.QLabel(parent=self.userRegister)
        self.alreadyHaveAccountText.setGeometry(QtCore.QRect(110, 527, 131, 41))
        self.alreadyHaveAccountText.setStyleSheet("color:white;")
        self.alreadyHaveAccountText.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.alreadyHaveAccountText.setObjectName("alreadyHaveAccountText")
        self.keyIconRegister = QtWidgets.QLabel(parent=self.userRegister)
        self.keyIconRegister.setGeometry(QtCore.QRect(50, 320, 30, 30))
        self.keyIconRegister.setText("")
        self.keyIconRegister.setPixmap(QtGui.QPixmap(":/icons/icons/key.png"))
        self.keyIconRegister.setScaledContents(True)
        self.keyIconRegister.setObjectName("keyIconRegister")
        self.emailIcon = QtWidgets.QLabel(parent=self.userRegister)
        self.emailIcon.setGeometry(QtCore.QRect(48, 214, 32, 32))
        self.emailIcon.setText("")
        self.emailIcon.setPixmap(QtGui.QPixmap(":/icons/icons/email.png"))
        self.emailIcon.setScaledContents(True)
        self.emailIcon.setObjectName("emailIcon")
        self.emailLineEditRegister = QtWidgets.QLineEdit(parent=self.userRegister)
        self.emailLineEditRegister.setGeometry(QtCore.QRect(88, 208, 251, 41))
        self.emailLineEditRegister.setStyleSheet("QLineEdit {\n"
"    background-color: #1e293b;   /* زمینه تیره */\n"
"    color: #e2e8f0;              /* متن روشن */\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"\n"
"    /* خط و عمق */\n"
"    border: 2px solid #0f172a;\n"
"    border-bottom: 4px solid #0a0f1c;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3b82f6;   /* آبی روشن */\n"
"    border-bottom: 4px solid #2563eb;\n"
"    outline: none;\n"
"}\n"
"")
        self.emailLineEditRegister.setMaxLength(100)
        self.emailLineEditRegister.setFrame(True)
        self.emailLineEditRegister.setCursorPosition(0)
        self.emailLineEditRegister.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.emailLineEditRegister.setClearButtonEnabled(True)
        self.emailLineEditRegister.setObjectName("emailLineEditRegister")
        self.passwordLineEditRegister = QtWidgets.QLineEdit(parent=self.userRegister)
        self.passwordLineEditRegister.setGeometry(QtCore.QRect(88, 318, 251, 41))
        self.passwordLineEditRegister.setStyleSheet("QLineEdit {\n"
"    background-color: #1e293b;   /* زمینه تیره */\n"
"    color: #e2e8f0;              /* متن روشن */\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"\n"
"    /* خط و عمق */\n"
"    border: 2px solid #0f172a;\n"
"    border-bottom: 4px solid #0a0f1c;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3b82f6;   /* آبی روشن */\n"
"    border-bottom: 4px solid #2563eb;\n"
"    outline: none;\n"
"}\n"
"")
        self.passwordLineEditRegister.setMaxLength(100)
        self.passwordLineEditRegister.setFrame(True)
        self.passwordLineEditRegister.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEditRegister.setCursorPosition(0)
        self.passwordLineEditRegister.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.passwordLineEditRegister.setClearButtonEnabled(True)
        self.passwordLineEditRegister.setObjectName("passwordLineEditRegister")
        self.headerTextRegister = QtWidgets.QLabel(parent=self.userRegister)
        self.headerTextRegister.setGeometry(QtCore.QRect(-10, 80, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(36)
        self.headerTextRegister.setFont(font)
        self.headerTextRegister.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.headerTextRegister.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerTextRegister.setObjectName("headerTextRegister")
        self.userIconRegister = QtWidgets.QLabel(parent=self.userRegister)
        self.userIconRegister.setGeometry(QtCore.QRect(48, 266, 32, 32))
        self.userIconRegister.setText("")
        self.userIconRegister.setPixmap(QtGui.QPixmap(":/icons/icons/user_for_login.png"))
        self.userIconRegister.setScaledContents(True)
        self.userIconRegister.setObjectName("userIconRegister")
        self.usernameLineEditRegister = QtWidgets.QLineEdit(parent=self.userRegister)
        self.usernameLineEditRegister.setGeometry(QtCore.QRect(88, 263, 251, 41))
        self.usernameLineEditRegister.setStyleSheet("QLineEdit {\n"
"    background-color: #1e293b;   /* زمینه تیره */\n"
"    color: #e2e8f0;              /* متن روشن */\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"\n"
"    /* خط و عمق */\n"
"    border: 2px solid #0f172a;\n"
"    border-bottom: 4px solid #0a0f1c;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3b82f6;   /* آبی روشن */\n"
"    border-bottom: 4px solid #2563eb;\n"
"    outline: none;\n"
"}\n"
"")
        self.usernameLineEditRegister.setMaxLength(100)
        self.usernameLineEditRegister.setFrame(True)
        self.usernameLineEditRegister.setCursorPosition(0)
        self.usernameLineEditRegister.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.usernameLineEditRegister.setClearButtonEnabled(True)
        self.usernameLineEditRegister.setObjectName("usernameLineEditRegister")
        self.confirmPasswordLineEditRegister = QtWidgets.QLineEdit(parent=self.userRegister)
        self.confirmPasswordLineEditRegister.setGeometry(QtCore.QRect(88, 373, 251, 41))
        self.confirmPasswordLineEditRegister.setStyleSheet("QLineEdit {\n"
"    background-color: #1e293b;   /* زمینه تیره */\n"
"    color: #e2e8f0;              /* متن روشن */\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"\n"
"    /* خط و عمق */\n"
"    border: 2px solid #0f172a;\n"
"    border-bottom: 4px solid #0a0f1c;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3b82f6;   /* آبی روشن */\n"
"    border-bottom: 4px solid #2563eb;\n"
"    outline: none;\n"
"}\n"
"")
        self.confirmPasswordLineEditRegister.setMaxLength(100)
        self.confirmPasswordLineEditRegister.setFrame(True)
        self.confirmPasswordLineEditRegister.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirmPasswordLineEditRegister.setCursorPosition(0)
        self.confirmPasswordLineEditRegister.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.confirmPasswordLineEditRegister.setClearButtonEnabled(True)
        self.confirmPasswordLineEditRegister.setObjectName("confirmPasswordLineEditRegister")
        self.confirmKeyIconRegister = QtWidgets.QLabel(parent=self.userRegister)
        self.confirmKeyIconRegister.setGeometry(QtCore.QRect(50, 380, 30, 30))
        self.confirmKeyIconRegister.setText("")
        self.confirmKeyIconRegister.setPixmap(QtGui.QPixmap(":/icons/icons/key.png"))
        self.confirmKeyIconRegister.setScaledContents(True)
        self.confirmKeyIconRegister.setObjectName("confirmKeyIconRegister")
        self.tabWidget.addTab(self.userRegister, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.usernameLineEdit, self.passwordLineEdit)
        Form.setTabOrder(self.passwordLineEdit, self.loginButton)
        Form.setTabOrder(self.loginButton, self.emailLineEditRegister)
        Form.setTabOrder(self.emailLineEditRegister, self.usernameLineEditRegister)
        Form.setTabOrder(self.usernameLineEditRegister, self.passwordLineEditRegister)
        Form.setTabOrder(self.passwordLineEditRegister, self.confirmPasswordLineEditRegister)
        Form.setTabOrder(self.confirmPasswordLineEditRegister, self.submitButton)
        Form.setTabOrder(self.submitButton, self.tabWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LithiumVPN - Login"))
        self.passwordLineEdit.setPlaceholderText(_translate("Form", "enter your password"))
        self.headerText.setText(_translate("Form", "LithiumVPN"))
        self.usernameLineEdit.setPlaceholderText(_translate("Form", "enter your username"))
        self.pTextLogin.setText(_translate("Form", "Login to your account"))
        self.loginButton.setText(_translate("Form", "Login"))
        self.dontHaveAccountText.setText(_translate("Form", "Dont have any account ?"))
        self.registerLinkText.setText(_translate("Form", " Create one for free"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.userLogin), _translate("Form", "Tab 1"))
        self.submitButton.setText(_translate("Form", "Submit"))
        self.pTextRegister.setText(_translate("Form", "Create your account"))
        self.loginLinkText.setText(_translate("Form", "Login"))
        self.alreadyHaveAccountText.setText(_translate("Form", "Already have account ? "))
        self.emailLineEditRegister.setPlaceholderText(_translate("Form", "enter your email address"))
        self.passwordLineEditRegister.setPlaceholderText(_translate("Form", "enter your password"))
        self.headerTextRegister.setText(_translate("Form", "LithiumVPN"))
        self.usernameLineEditRegister.setPlaceholderText(_translate("Form", "enter your username"))
        self.confirmPasswordLineEditRegister.setPlaceholderText(_translate("Form", "confirm your password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.userRegister), _translate("Form", "Tab 2"))
