# Form implementation generated from reading ui file 'design/dotui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 630)
        MainWindow.setMinimumSize(QtCore.QSize(400, 630))
        MainWindow.setMaximumSize(QtCore.QSize(400, 630))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(15, 23, 42)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -30, 400, 681))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.profileIcon = QtWidgets.QLabel(parent=self.homeTab)
        self.profileIcon.setGeometry(QtCore.QRect(15, 20, 48, 48))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.profileIcon.setFont(font)
        self.profileIcon.setText("")
        self.profileIcon.setPixmap(QtGui.QPixmap(":/icons/icons/user.png"))
        self.profileIcon.setScaledContents(True)
        self.profileIcon.setObjectName("profileIcon")
        self.connectionStatusText = QtWidgets.QLabel(parent=self.homeTab)
        self.connectionStatusText.setGeometry(QtCore.QRect(110, 405, 201, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(16)
        self.connectionStatusText.setFont(font)
        self.connectionStatusText.setStyleSheet("color:rgb(148, 163, 184)")
        self.connectionStatusText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.connectionStatusText.setObjectName("connectionStatusText")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.homeTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 109, 78, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.coinLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.coinLayout.setContentsMargins(0, 0, 0, 0)
        self.coinLayout.setObjectName("coinLayout")
        self.coinNumber = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.coinNumber.setFont(font)
        self.coinNumber.setStyleSheet("color:white;")
        self.coinNumber.setObjectName("coinNumber")
        self.coinLayout.addWidget(self.coinNumber)
        self.coinIcon = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.coinIcon.setEnabled(False)
        self.coinIcon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/coin.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/coin.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.coinIcon.setIcon(icon)
        self.coinIcon.setCheckable(False)
        self.coinIcon.setFlat(True)
        self.coinIcon.setObjectName("coinIcon")
        self.coinLayout.addWidget(self.coinIcon)
        self.usernameText = QtWidgets.QLabel(parent=self.homeTab)
        self.usernameText.setGeometry(QtCore.QRect(30, 69, 81, 39))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.usernameText.setFont(font)
        self.usernameText.setStyleSheet("color:white;")
        self.usernameText.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.usernameText.setObjectName("usernameText")
        self.selectConfigComboBox = QtWidgets.QComboBox(parent=self.homeTab)
        self.selectConfigComboBox.setGeometry(QtCore.QRect(110, 455, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.selectConfigComboBox.setFont(font)
        self.selectConfigComboBox.setStyleSheet("QScrollBar:vertical {\n"
"    background: #f0f0f0;   /* پس زمینه */\n"
"    width: 10px;           /* ضخامت اسکرول بار */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #888;      /* رنگ دستگیره (قابل حرکت) */\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #555;      /* رنگ دستگیره وقتی موس روشه */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;      /* دکمه‌های بالا/پایین رو حذف میکنه */\n"
"}\n"
"QComboBox{\n"
"color:white;\n"
"}\n"
"")
        self.selectConfigComboBox.setMaxVisibleItems(3)
        self.selectConfigComboBox.setObjectName("selectConfigComboBox")
        self.selectConfigComboBox.addItem("")
        self.selectConfigComboBox.addItem("")
        self.selectConfigComboBox.addItem("")
        self.selectConfigComboBox.addItem("")
        self.selectConfigComboBox.addItem("")
        self.continueProfileLine = QtWidgets.QFrame(parent=self.homeTab)
        self.continueProfileLine.setGeometry(QtCore.QRect(11, 63, 20, 71))
        self.continueProfileLine.setStyleSheet("color:rgb(230, 230, 230)")
        self.continueProfileLine.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.continueProfileLine.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.continueProfileLine.setLineWidth(2)
        self.continueProfileLine.setObjectName("continueProfileLine")
        self.powerButtonBase = QtWidgets.QPushButton(parent=self.homeTab)
        self.powerButtonBase.setGeometry(QtCore.QRect(105, 170, 210, 210))
        self.powerButtonBase.setStyleSheet("border-radius : 100; \n"
"background-color: white")
        self.powerButtonBase.setText("")
        self.powerButtonBase.setIconSize(QtCore.QSize(110, 110))
        self.powerButtonBase.setObjectName("powerButtonBase")
        self.powerButton = QtWidgets.QPushButton(parent=self.homeTab)
        self.powerButton.setGeometry(QtCore.QRect(110, 175, 200, 200))
        self.powerButton.setStyleSheet("border-radius : 100; \n"
"background-color: qlineargradient(spread:pad, x1:0.462, y1:0, x2:0.473, y2:1, stop:0 rgba(107, 114, 128, 255), stop:1 rgba(210, 220, 236, 255))")
        self.powerButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/power.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.powerButton.setIcon(icon1)
        self.powerButton.setIconSize(QtCore.QSize(150, 150))
        self.powerButton.setObjectName("powerButton")
        self.headerText = QtWidgets.QLabel(parent=self.homeTab)
        self.headerText.setGeometry(QtCore.QRect(77, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(28)
        self.headerText.setFont(font)
        self.headerText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.headerText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerText.setObjectName("headerText")
        self.dragframe_home = QtWidgets.QFrame(parent=self.homeTab)
        self.dragframe_home.setGeometry(QtCore.QRect(-3, 0, 400, 121))
        self.dragframe_home.setStyleSheet("background-color:transparent;")
        self.dragframe_home.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dragframe_home.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dragframe_home.setObjectName("dragframe_home")
        self.tabWidget.addTab(self.homeTab, "")
        self.accountTab = QtWidgets.QWidget()
        self.accountTab.setObjectName("accountTab")
        self.accountPersonImage = QtWidgets.QLabel(parent=self.accountTab)
        self.accountPersonImage.setGeometry(QtCore.QRect(100, 130, 191, 191))
        self.accountPersonImage.setText("")
        self.accountPersonImage.setPixmap(QtGui.QPixmap(":/icons/icons/user.png"))
        self.accountPersonImage.setScaledContents(True)
        self.accountPersonImage.setObjectName("accountPersonImage")
        self.accountUsernameText = QtWidgets.QLabel(parent=self.accountTab)
        self.accountUsernameText.setGeometry(QtCore.QRect(0, 320, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.accountUsernameText.setFont(font)
        self.accountUsernameText.setStyleSheet("color:white;")
        self.accountUsernameText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountUsernameText.setObjectName("accountUsernameText")
        self.accountCoinsCount = QtWidgets.QLabel(parent=self.accountTab)
        self.accountCoinsCount.setGeometry(QtCore.QRect(225, 435, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.accountCoinsCount.setFont(font)
        self.accountCoinsCount.setStyleSheet("color:white;")
        self.accountCoinsCount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountCoinsCount.setObjectName("accountCoinsCount")
        self.accountCoinsIcon = QtWidgets.QLabel(parent=self.accountTab)
        self.accountCoinsIcon.setGeometry(QtCore.QRect(260, 437, 16, 16))
        self.accountCoinsIcon.setText("")
        self.accountCoinsIcon.setPixmap(QtGui.QPixmap(":/icons/icons/coin.png"))
        self.accountCoinsIcon.setScaledContents(True)
        self.accountCoinsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountCoinsIcon.setObjectName("accountCoinsIcon")
        self.accountEmailText = QtWidgets.QLabel(parent=self.accountTab)
        self.accountEmailText.setGeometry(QtCore.QRect(0, 350, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.accountEmailText.setFont(font)
        self.accountEmailText.setStyleSheet("color:white;")
        self.accountEmailText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountEmailText.setObjectName("accountEmailText")
        self.accountCoinsText = QtWidgets.QLabel(parent=self.accountTab)
        self.accountCoinsText.setGeometry(QtCore.QRect(110, 435, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.accountCoinsText.setFont(font)
        self.accountCoinsText.setStyleSheet("color:white;")
        self.accountCoinsText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountCoinsText.setObjectName("accountCoinsText")
        self.accountAllConfigsText = QtWidgets.QLabel(parent=self.accountTab)
        self.accountAllConfigsText.setGeometry(QtCore.QRect(110, 465, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.accountAllConfigsText.setFont(font)
        self.accountAllConfigsText.setStyleSheet("color:white;")
        self.accountAllConfigsText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountAllConfigsText.setObjectName("accountAllConfigsText")
        self.accountAllConfigsCount = QtWidgets.QLabel(parent=self.accountTab)
        self.accountAllConfigsCount.setGeometry(QtCore.QRect(235, 465, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.accountAllConfigsCount.setFont(font)
        self.accountAllConfigsCount.setStyleSheet("color:white;")
        self.accountAllConfigsCount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountAllConfigsCount.setObjectName("accountAllConfigsCount")
        self.accountSpacer = QtWidgets.QFrame(parent=self.accountTab)
        self.accountSpacer.setGeometry(QtCore.QRect(60, 400, 270, 16))
        self.accountSpacer.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.accountSpacer.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.accountSpacer.setObjectName("accountSpacer")
        self.accountExpiredConfigsText = QtWidgets.QLabel(parent=self.accountTab)
        self.accountExpiredConfigsText.setGeometry(QtCore.QRect(114, 495, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.accountExpiredConfigsText.setFont(font)
        self.accountExpiredConfigsText.setStyleSheet("color:white;")
        self.accountExpiredConfigsText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountExpiredConfigsText.setObjectName("accountExpiredConfigsText")
        self.accountExpiredConfigsCount = QtWidgets.QLabel(parent=self.accountTab)
        self.accountExpiredConfigsCount.setGeometry(QtCore.QRect(270, 495, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(11)
        self.accountExpiredConfigsCount.setFont(font)
        self.accountExpiredConfigsCount.setStyleSheet("color:white;")
        self.accountExpiredConfigsCount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountExpiredConfigsCount.setObjectName("accountExpiredConfigsCount")
        self.accountlogoutButton = QtWidgets.QPushButton(parent=self.accountTab)
        self.accountlogoutButton.setGeometry(QtCore.QRect(70, 530, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.accountlogoutButton.setFont(font)
        self.accountlogoutButton.setStyleSheet("QPushButton#accountlogoutButton {\n"
"    background-color: #b91c1c;        /* قرمز تیره برای پس‌زمینه */\n"
"    color: #f8fafc;                   /* متن سفید مایل به خاکستری */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    font-weight: bold;\n"
"\n"
"    /* عمق (سایه‌ی مصنوعی) */\n"
"    border: 2px solid #7f1d1d;        /* خط دور تیره‌تر */\n"
"    border-bottom: 4px solid #450a0a; /* سایه پایین برای برجسته شدن */\n"
"\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton#accountlogoutButton:hover {\n"
"    background-color: #dc2626;        /* کمی روشن‌تر هنگام hover */\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#accountlogoutButton:pressed {\n"
"    background-color: #991b1b;        /* کمی تیره‌تر هنگام فشار */\n"
"    border: 2px solid #450a0a;\n"
"    border-top: 4px solid #450a0a;    /* سایه بالا برای حس فرو رفتن */\n"
"    padding-top: 12px;                /* حرکت جزئی برای طبیعی‌تر شدن */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.accountlogoutButton.setObjectName("accountlogoutButton")
        self.accountHeaderText = QtWidgets.QLabel(parent=self.accountTab)
        self.accountHeaderText.setGeometry(QtCore.QRect(77, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(28)
        self.accountHeaderText.setFont(font)
        self.accountHeaderText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.accountHeaderText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.accountHeaderText.setObjectName("accountHeaderText")
        self.dragframe_account = QtWidgets.QFrame(parent=self.accountTab)
        self.dragframe_account.setGeometry(QtCore.QRect(-3, 0, 400, 111))
        self.dragframe_account.setStyleSheet("background-color:transparent;")
        self.dragframe_account.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dragframe_account.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dragframe_account.setObjectName("dragframe_account")
        self.tabWidget.addTab(self.accountTab, "")
        self.configsTab = QtWidgets.QWidget()
        self.configsTab.setObjectName("configsTab")
        self.myConfigsHeaderText = QtWidgets.QLabel(parent=self.configsTab)
        self.myConfigsHeaderText.setGeometry(QtCore.QRect(77, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(28)
        self.myConfigsHeaderText.setFont(font)
        self.myConfigsHeaderText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.myConfigsHeaderText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.myConfigsHeaderText.setObjectName("myConfigsHeaderText")
        self.myconfigs_scrollArea = QtWidgets.QScrollArea(parent=self.configsTab)
        self.myconfigs_scrollArea.setGeometry(QtCore.QRect(0, 80, 395, 521))
        self.myconfigs_scrollArea.setStyleSheet("/* ===== پایه - برای همه‌ی QScrollBar ها ===== */\n"
"QScrollBar:vertical {\n"
"    background: transparent;        /* پس‌زمینه‌ی خودِ groove شفاف */\n"
"    width: 12px;                    /* ضخامت اسکرول‌بار */\n"
"    margin: 6px 0px 6px 0px;        /* تا handle به لبه‌ها نچسبه */\n"
"}\n"
"\n"
"/* اگر می‌خواهی فقط برای QScrollArea اعمال کنی:\n"
"   QScrollArea QScrollBar:vertical { ... }\n"
"*/\n"
"\n"
"/* groove (راهروی اسکرول؛ ما آن‌را هم کمی گرد می‌کنیم) */\n"
"QScrollBar::groove:vertical {\n"
"    background: transparent;        /* یا rgba(..., 0.06) برای کمی کانتور */\n"
"    border-radius: 7px;\n"
"    margin: 0px;                    /* groove خودش با margin handle فاصله میگیره */\n"
"}\n"
"\n"
"/* handle — همان دکمه‌ای که حرکت می‌کند */\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(255,255,255,0.85);   /* سفیدِ مات (0.85 شفافیت) */\n"
"    min-height: 36px;                     /* حداقل اندازه‌ی handle */\n"
"    border-radius: 999px;                 /* خیلی بزرگ => همیشه گرد */\n"
"    border: 1px solid rgba(255,255,255,0.25);\n"
"    margin: 4px 2px 4px 2px;              /* خیلی مهم برای دیدن گوشه‌های گرد */\n"
"}\n"
"\n"
"/* وقتی ماوس روشه کمی برجسته‌ترش کن */\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(255,255,255,0.95);\n"
"}\n"
"\n"
"/* وقتی کلیک می‌کنن ــ حس فشرده شدن */\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background: rgba(255,255,255,1.0);\n"
"    margin-top: 5px;      /* اندکی جابه‌جایی عمودی برای حس فشرده‌شدن */\n"
"}\n"
"\n"
"/* مخفی کردن دکمه‌های بالا/پایین (arrow buttons) */\n"
"QScrollBar::sub-line:vertical, QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-origin: padding;\n"
"}\n"
"\n"
"/* صفحه خالی بین handle و لبه (برای کلیک روی groove) */\n"
"QScrollBar::sub-page:vertical, QScrollBar::add-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* ===== برای اسکرول‌بار افقی هم همان‌ها با عرض/height معکوس ===== */\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 12px;\n"
"    margin: 0px 6px 0px 6px;\n"
"}\n"
"QScrollBar::groove:horizontal { border-radius: 7px; background: transparent; }\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(255,255,255,0.85);\n"
"    min-width: 36px;\n"
"    border-radius: 999px;\n"
"    border: 1px solid rgba(255,255,255,0.25);\n"
"    margin: 2px 4px 2px 4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover { background: rgba(255,255,255,0.95); }\n"
"QScrollBar::sub-line:horizontal, QScrollBar::add-line:horizontal { width: 0px; }\n"
"QScrollBar::sub-page:horizontal, QScrollBar::add-page:horizontal { background: transparent; }\n"
"QScrollBar{\n"
"border-radius: 12px;\n"
"border: 1px solid #555;\n"
"}")
        self.myconfigs_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.myconfigs_scrollArea.setWidgetResizable(True)
        self.myconfigs_scrollArea.setObjectName("myconfigs_scrollArea")
        self.myconfigs_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.myconfigs_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 393, 519))
        self.myconfigs_scrollAreaWidgetContents.setObjectName("myconfigs_scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.myconfigs_scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.myconfigs_mainContainer = QtWidgets.QVBoxLayout()
        self.myconfigs_mainContainer.setContentsMargins(8, 8, 8, 8)
        self.myconfigs_mainContainer.setSpacing(8)
        self.myconfigs_mainContainer.setObjectName("myconfigs_mainContainer")
        self.verticalLayout_4.addLayout(self.myconfigs_mainContainer)
        self.myconfigs_scrollArea.setWidget(self.myconfigs_scrollAreaWidgetContents)
        self.dragframe_myconfigs = QtWidgets.QFrame(parent=self.configsTab)
        self.dragframe_myconfigs.setGeometry(QtCore.QRect(-3, 0, 400, 80))
        self.dragframe_myconfigs.setStyleSheet("background-color:transparent;")
        self.dragframe_myconfigs.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dragframe_myconfigs.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dragframe_myconfigs.setObjectName("dragframe_myconfigs")
        self.tabWidget.addTab(self.configsTab, "")
        self.buyConfigsTab = QtWidgets.QWidget()
        self.buyConfigsTab.setObjectName("buyConfigsTab")
        self.buyConfigsHeaderText = QtWidgets.QLabel(parent=self.buyConfigsTab)
        self.buyConfigsHeaderText.setGeometry(QtCore.QRect(77, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(28)
        self.buyConfigsHeaderText.setFont(font)
        self.buyConfigsHeaderText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.buyConfigsHeaderText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.buyConfigsHeaderText.setObjectName("buyConfigsHeaderText")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.buyConfigsTab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 80, 391, 521))
        self.scrollArea.setStyleSheet("/* ===== پایه - برای همه‌ی QScrollBar ها ===== */\n"
"QScrollBar:vertical {\n"
"    background: transparent;        /* پس‌زمینه‌ی خودِ groove شفاف */\n"
"    width: 12px;                    /* ضخامت اسکرول‌بار */\n"
"    margin: 6px 0px 6px 0px;        /* تا handle به لبه‌ها نچسبه */\n"
"}\n"
"\n"
"/* اگر می‌خواهی فقط برای QScrollArea اعمال کنی:\n"
"   QScrollArea QScrollBar:vertical { ... }\n"
"*/\n"
"\n"
"/* groove (راهروی اسکرول؛ ما آن‌را هم کمی گرد می‌کنیم) */\n"
"QScrollBar::groove:vertical {\n"
"    background: transparent;        /* یا rgba(..., 0.06) برای کمی کانتور */\n"
"    border-radius: 7px;\n"
"    margin: 0px;                    /* groove خودش با margin handle فاصله میگیره */\n"
"}\n"
"\n"
"/* handle — همان دکمه‌ای که حرکت می‌کند */\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(255,255,255,0.85);   /* سفیدِ مات (0.85 شفافیت) */\n"
"    min-height: 36px;                     /* حداقل اندازه‌ی handle */\n"
"    border-radius: 999px;                 /* خیلی بزرگ => همیشه گرد */\n"
"    border: 1px solid rgba(255,255,255,0.25);\n"
"    margin: 4px 2px 4px 2px;              /* خیلی مهم برای دیدن گوشه‌های گرد */\n"
"}\n"
"\n"
"/* وقتی ماوس روشه کمی برجسته‌ترش کن */\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(255,255,255,0.95);\n"
"}\n"
"\n"
"/* وقتی کلیک می‌کنن ــ حس فشرده شدن */\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background: rgba(255,255,255,1.0);\n"
"    margin-top: 5px;      /* اندکی جابه‌جایی عمودی برای حس فشرده‌شدن */\n"
"}\n"
"\n"
"/* مخفی کردن دکمه‌های بالا/پایین (arrow buttons) */\n"
"QScrollBar::sub-line:vertical, QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-origin: padding;\n"
"}\n"
"\n"
"/* صفحه خالی بین handle و لبه (برای کلیک روی groove) */\n"
"QScrollBar::sub-page:vertical, QScrollBar::add-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* ===== برای اسکرول‌بار افقی هم همان‌ها با عرض/height معکوس ===== */\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 12px;\n"
"    margin: 0px 6px 0px 6px;\n"
"}\n"
"QScrollBar::groove:horizontal { border-radius: 7px; background: transparent; }\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(255,255,255,0.85);\n"
"    min-width: 36px;\n"
"    border-radius: 999px;\n"
"    border: 1px solid rgba(255,255,255,0.25);\n"
"    margin: 2px 4px 2px 4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover { background: rgba(255,255,255,0.95); }\n"
"QScrollBar::sub-line:horizontal, QScrollBar::add-line:horizontal { width: 0px; }\n"
"QScrollBar::sub-page:horizontal, QScrollBar::add-page:horizontal { background: transparent; }\n"
"QScrollBar{\n"
"border-radius: 12px;\n"
"border: 1px solid #555;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 389, 519))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.dragframe_buyconfig = QtWidgets.QFrame(parent=self.buyConfigsTab)
        self.dragframe_buyconfig.setGeometry(QtCore.QRect(-3, 0, 400, 80))
        self.dragframe_buyconfig.setStyleSheet("background-color:transparent;")
        self.dragframe_buyconfig.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dragframe_buyconfig.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dragframe_buyconfig.setObjectName("dragframe_buyconfig")
        self.tabWidget.addTab(self.buyConfigsTab, "")
        self.buyCoinsTab = QtWidgets.QWidget()
        self.buyCoinsTab.setObjectName("buyCoinsTab")
        self.buyCoinsHeaderText = QtWidgets.QLabel(parent=self.buyCoinsTab)
        self.buyCoinsHeaderText.setGeometry(QtCore.QRect(77, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(28)
        self.buyCoinsHeaderText.setFont(font)
        self.buyCoinsHeaderText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.buyCoinsHeaderText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.buyCoinsHeaderText.setObjectName("buyCoinsHeaderText")
        self.buyCoinsAdminID = QtWidgets.QLabel(parent=self.buyCoinsTab)
        self.buyCoinsAdminID.setGeometry(QtCore.QRect(0, 255, 393, 51))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(28)
        self.buyCoinsAdminID.setFont(font)
        self.buyCoinsAdminID.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.buyCoinsAdminID.setObjectName("buyCoinsAdminID")
        self.buyCoinsDescription = QtWidgets.QLabel(parent=self.buyCoinsTab)
        self.buyCoinsDescription.setGeometry(QtCore.QRect(74, 308, 251, 21))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.buyCoinsDescription.setFont(font)
        self.buyCoinsDescription.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.buyCoinsDescription.setObjectName("buyCoinsDescription")
        self.buyCoinsCoinIcon = QtWidgets.QLabel(parent=self.buyCoinsTab)
        self.buyCoinsCoinIcon.setGeometry(QtCore.QRect(330, 310, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.buyCoinsCoinIcon.setFont(font)
        self.buyCoinsCoinIcon.setText("")
        self.buyCoinsCoinIcon.setPixmap(QtGui.QPixmap(":/icons/icons/coin.png"))
        self.buyCoinsCoinIcon.setScaledContents(True)
        self.buyCoinsCoinIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.buyCoinsCoinIcon.setObjectName("buyCoinsCoinIcon")
        self.buyCoinsUserIcon = QtWidgets.QLabel(parent=self.buyCoinsTab)
        self.buyCoinsUserIcon.setGeometry(QtCore.QRect(158, 180, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.buyCoinsUserIcon.setFont(font)
        self.buyCoinsUserIcon.setText("")
        self.buyCoinsUserIcon.setPixmap(QtGui.QPixmap(":/icons/icons/user.png"))
        self.buyCoinsUserIcon.setScaledContents(True)
        self.buyCoinsUserIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.buyCoinsUserIcon.setObjectName("buyCoinsUserIcon")
        self.buyCoinsBuyButton = QtWidgets.QPushButton(parent=self.buyCoinsTab)
        self.buyCoinsBuyButton.setGeometry(QtCore.QRect(73, 340, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(14)
        font.setBold(True)
        self.buyCoinsBuyButton.setFont(font)
        self.buyCoinsBuyButton.setStyleSheet("QPushButton#buyCoinsBuyButton {\n"
"    background-color: #059669;        /* سبز آبی اصلی (primary) */\n"
"    color: #f8fafc;                   /* متن روشن */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    font-weight: bold;\n"
"\n"
"    /* عمق و برجستگی */\n"
"    border: 2px solid #047857;        /* خط دور کمی تیره‌تر */\n"
"    border-bottom: 4px solid #065f46; /* سایه پایین برای حجم دادن */\n"
"\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Hover - روشن‌تر و زنده‌تر */\n"
"QPushButton#buyCoinsBuyButton:hover {\n"
"    background-color: #10b981;        /* سبز روشن‌تر هنگام hover */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Pressed - کمی تیره‌تر و با حرکت جزئی */\n"
"QPushButton#buyCoinsBuyButton:pressed {\n"
"    background-color: #047857;        /* سبز تیره‌تر */\n"
"    border: 2px solid #065f46;\n"
"    border-top: 4px solid #065f46;    /* سایه بالا برای حس فرو رفتن */\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.buyCoinsBuyButton.setObjectName("buyCoinsBuyButton")
        self.buyCoinsCoinIcon_2 = QtWidgets.QLabel(parent=self.buyCoinsTab)
        self.buyCoinsCoinIcon_2.setGeometry(QtCore.QRect(53, 310, 16, 16))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        self.buyCoinsCoinIcon_2.setFont(font)
        self.buyCoinsCoinIcon_2.setText("")
        self.buyCoinsCoinIcon_2.setPixmap(QtGui.QPixmap(":/icons/icons/coin.png"))
        self.buyCoinsCoinIcon_2.setScaledContents(True)
        self.buyCoinsCoinIcon_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.buyCoinsCoinIcon_2.setObjectName("buyCoinsCoinIcon_2")
        self.dragframe_buycoin = QtWidgets.QFrame(parent=self.buyCoinsTab)
        self.dragframe_buycoin.setGeometry(QtCore.QRect(-3, 0, 400, 111))
        self.dragframe_buycoin.setStyleSheet("background-color:transparent;")
        self.dragframe_buycoin.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dragframe_buycoin.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dragframe_buycoin.setObjectName("dragframe_buycoin")
        self.tabWidget.addTab(self.buyCoinsTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.settingsHeaderText = QtWidgets.QLabel(parent=self.settingsTab)
        self.settingsHeaderText.setGeometry(QtCore.QRect(77, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(28)
        self.settingsHeaderText.setFont(font)
        self.settingsHeaderText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.settingsHeaderText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.settingsHeaderText.setObjectName("settingsHeaderText")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.settingsTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(7, 110, 381, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.settingsProxyExclusivesLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.settingsProxyExclusivesLayout.setContentsMargins(12, 12, 12, 12)
        self.settingsProxyExclusivesLayout.setSpacing(10)
        self.settingsProxyExclusivesLayout.setObjectName("settingsProxyExclusivesLayout")
        self.settingsProxyExclusivesTopicText = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.settingsProxyExclusivesTopicText.setFont(font)
        self.settingsProxyExclusivesTopicText.setToolTip("")
        self.settingsProxyExclusivesTopicText.setStatusTip("")
        self.settingsProxyExclusivesTopicText.setWhatsThis("")
        self.settingsProxyExclusivesTopicText.setStyleSheet("color:rgb(125, 200, 255);")
        self.settingsProxyExclusivesTopicText.setObjectName("settingsProxyExclusivesTopicText")
        self.settingsProxyExclusivesLayout.addWidget(self.settingsProxyExclusivesTopicText)
        self.settingsProxyExclusivesTextEdit = QtWidgets.QPlainTextEdit(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(1)
        self.settingsProxyExclusivesTextEdit.setFont(font)
        self.settingsProxyExclusivesTextEdit.setToolTip("")
        self.settingsProxyExclusivesTextEdit.setStyleSheet("QPlainTextEdit#settingsProxyExclusivesTextEdit {\n"
"    background-color: rgb(19, 28, 44);\n"
"    color: #e6eef6;\n"
"    border: 1px solid rgba(17,186,189,160);\n"
"    border-radius: 12px;\n"
"    padding: 12px;\n"
"    font-family: Consolas, \"Courier New\", monospace;\n"
"    font-size: 13px;\n"
"    selection-background-color: rgba(59,130,246,0.25);\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit:focus {\n"
"    border: 1px solid rgba(59,130,246,220);\n"
"    background-color: rgb(21, 34, 58);\n"
"}\n"
"\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 12px;\n"
"    margin: 6px 0px 6px 0px;\n"
"}\n"
"\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::groove:vertical {\n"
"    background: rgba(255,255,255,0.02);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::handle:vertical {\n"
"    background: rgba(255,255,255,0.85);\n"
"    min-height: 36px;\n"
"    border-radius: 999px;\n"
"    border: 1px solid rgba(255,255,255,0.25);\n"
"    margin: 4px 2px 4px 2px;\n"
"}\n"
"\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::handle:vertical:hover {\n"
"    background: rgba(255,255,255,0.95);\n"
"}\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::handle:vertical:pressed {\n"
"    background: rgba(255,255,255,1.0);\n"
"    margin-top: 5px;\n"
"}\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::sub-line:vertical,\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::sub-page:vertical,\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::add-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar:horizontal { height: 12px; margin: 0px 6px; }\n"
"QPlainTextEdit#settingsProxyExclusivesTextEdit QScrollBar::handle:horizontal {\n"
"    background: rgba(255,255,255,0.85);\n"
"    min-width: 36px;\n"
"    border-radius: 999px;\n"
"    border: 1px solid rgba(255,255,255,0.25);\n"
"    margin: 2px 4px 2px 4px;\n"
"}")
        self.settingsProxyExclusivesTextEdit.setObjectName("settingsProxyExclusivesTextEdit")
        self.settingsProxyExclusivesLayout.addWidget(self.settingsProxyExclusivesTextEdit)
        self.settingsProxyExclusivesApplyButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        self.settingsProxyExclusivesApplyButton.setFont(font)
        self.settingsProxyExclusivesApplyButton.setStyleSheet("QPushButton#settingsProxyExclusivesApplyButton {\n"
"    /* رنگِ تنظیمات: یک آبی-سرد ملایم (هماهنگ با selection و focus) */\n"
"    background-color: #2563EB;   /* blue-600 */\n"
"    color: #f8fafc;\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1e40af;   /* آبی تیره‌تر برای کنتراست */\n"
"    border-bottom: 4px solid #122055;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* hover و pressed — از استایل قبلی استفاده می‌کنیم ولی با همان رنگ‌بندی آبی */\n"
"QPushButton#settingsProxyExclusivesApplyButton:hover {\n"
"    background-color: #3b82f6;\n"
"}\n"
"QPushButton#settingsProxyExclusivesApplyButton:pressed {\n"
"    background-color: #1e40af;\n"
"    border: 2px solid #122055;\n"
"    border-top: 4px solid #122055;\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;\n"
"}")
        self.settingsProxyExclusivesApplyButton.setObjectName("settingsProxyExclusivesApplyButton")
        self.settingsProxyExclusivesLayout.addWidget(self.settingsProxyExclusivesApplyButton)
        self.dragframe_settings = QtWidgets.QFrame(parent=self.settingsTab)
        self.dragframe_settings.setGeometry(QtCore.QRect(-3, 0, 400, 90))
        self.dragframe_settings.setStyleSheet("background-color:transparent;")
        self.dragframe_settings.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dragframe_settings.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dragframe_settings.setObjectName("dragframe_settings")
        self.tabWidget.addTab(self.settingsTab, "")
        self.sideMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.sideMenu.setGeometry(QtCore.QRect(400, 85, 111, 341))
        self.sideMenu.setStyleSheet("/*background-color: rgb(30, 41, 59);*/\n"
"\n"
"\n"
"#sideMenu {\n"
"    background-color: rgb(30, 41, 59); /* پس‌زمینه منو */\n"
"    border-radius:14px;\n"
"}\n"
"\n"
"#sideMenu QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(241, 245, 249);\n"
"    padding: 8px 16px;\n"
"    text-align: left;\n"
"    border: none;\n"
"}\n"
"\n"
"#sideMenu QPushButton:hover {\n"
"    background-color: rgb(51, 65, 85);\n"
"}\n"
"\n"
"#sideMenu QPushButton:checked {\n"
"    background-color: rgb(59, 130, 246); /* آبی برای آیتم انتخاب‌شده */\n"
"    color: white;\n"
"}")
        self.sideMenu.setObjectName("sideMenu")
        self.sideMenuHomeButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuHomeButton.setGeometry(QtCore.QRect(0, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuHomeButton.setFont(font)
        self.sideMenuHomeButton.setObjectName("sideMenuHomeButton")
        self.sideMenuAccountButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuAccountButton.setGeometry(QtCore.QRect(0, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuAccountButton.setFont(font)
        self.sideMenuAccountButton.setObjectName("sideMenuAccountButton")
        self.sideMenuConfigsButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuConfigsButton.setGeometry(QtCore.QRect(0, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuConfigsButton.setFont(font)
        self.sideMenuConfigsButton.setObjectName("sideMenuConfigsButton")
        self.sideMenuBuyConfigsButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuBuyConfigsButton.setGeometry(QtCore.QRect(0, 180, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuBuyConfigsButton.setFont(font)
        self.sideMenuBuyConfigsButton.setObjectName("sideMenuBuyConfigsButton")
        self.sideMenuSettingsButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuSettingsButton.setGeometry(QtCore.QRect(0, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuSettingsButton.setFont(font)
        self.sideMenuSettingsButton.setObjectName("sideMenuSettingsButton")
        self.sideMenuBuyCoinsButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuBuyCoinsButton.setGeometry(QtCore.QRect(0, 230, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuBuyCoinsButton.setFont(font)
        self.sideMenuBuyCoinsButton.setObjectName("sideMenuBuyCoinsButton")
        self.menuButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.menuButton.setGeometry(QtCore.QRect(330, 102, 51, 41))
        self.menuButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuButton.setIcon(icon2)
        self.menuButton.setIconSize(QtCore.QSize(30, 48))
        self.menuButton.setFlat(True)
        self.menuButton.setObjectName("menuButton")
        self.minbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minbutton.setGeometry(QtCore.QRect(332, 62, 46, 35))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.minbutton.setFont(font)
        self.minbutton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton::before {\n"
"    content: \"\";\n"
"    position: absolute;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 55);\n"
"    border-color: rgba(255, 255, 255, 180);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 85);\n"
"}\n"
"")
        self.minbutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/minicon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minbutton.setIcon(icon3)
        self.minbutton.setObjectName("minbutton")
        self.closebutton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closebutton.setGeometry(QtCore.QRect(332, 20, 46, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.closebutton.setFont(font)
        self.closebutton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border: 1px solid rgba(255, 255, 255, 100);\n"
"    border-radius: 6px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton::before {\n"
"    content: \"\";\n"
"    position: absolute;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 55);\n"
"    border-color: rgba(255, 255, 255, 180);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 85);\n"
"}\n"
"")
        self.closebutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/closebutton.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closebutton.setIcon(icon4)
        self.closebutton.setIconSize(QtCore.QSize(20, 20))
        self.closebutton.setObjectName("closebutton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LithiumVPN"))
        self.connectionStatusText.setText(_translate("MainWindow", "Not Connected"))
        self.coinNumber.setText(_translate("MainWindow", "999"))
        self.usernameText.setText(_translate("MainWindow", "Username"))
        self.selectConfigComboBox.setPlaceholderText(_translate("MainWindow", "select config"))
        self.selectConfigComboBox.setItemText(0, _translate("MainWindow", "item1"))
        self.selectConfigComboBox.setItemText(1, _translate("MainWindow", "item2"))
        self.selectConfigComboBox.setItemText(2, _translate("MainWindow", "item3"))
        self.selectConfigComboBox.setItemText(3, _translate("MainWindow", "item4"))
        self.selectConfigComboBox.setItemText(4, _translate("MainWindow", "item5"))
        self.headerText.setText(_translate("MainWindow", "LithiumVPN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), _translate("MainWindow", "Tab 1"))
        self.accountUsernameText.setText(_translate("MainWindow", "username"))
        self.accountCoinsCount.setText(_translate("MainWindow", "999"))
        self.accountEmailText.setText(_translate("MainWindow", "email@gmail.com"))
        self.accountCoinsText.setText(_translate("MainWindow", "coins left :"))
        self.accountAllConfigsText.setText(_translate("MainWindow", "all configs :"))
        self.accountAllConfigsCount.setText(_translate("MainWindow", "20"))
        self.accountExpiredConfigsText.setText(_translate("MainWindow", "expired configs :"))
        self.accountExpiredConfigsCount.setText(_translate("MainWindow", "19"))
        self.accountlogoutButton.setText(_translate("MainWindow", "Logout"))
        self.accountHeaderText.setText(_translate("MainWindow", "LithiumVPN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accountTab), _translate("MainWindow", "Tab 2"))
        self.myConfigsHeaderText.setText(_translate("MainWindow", "LithiumVPN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configsTab), _translate("MainWindow", "Page"))
        self.buyConfigsHeaderText.setText(_translate("MainWindow", "LithiumVPN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buyConfigsTab), _translate("MainWindow", "Page"))
        self.buyCoinsHeaderText.setText(_translate("MainWindow", "LithiumVPN"))
        self.buyCoinsAdminID.setText(_translate("MainWindow", "@MibroAdmin"))
        self.buyCoinsDescription.setText(_translate("MainWindow", "Message in telegram for buying coins"))
        self.buyCoinsBuyButton.setText(_translate("MainWindow", "Buy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buyCoinsTab), _translate("MainWindow", "Page"))
        self.settingsHeaderText.setText(_translate("MainWindow", "LithiumVPN"))
        self.settingsProxyExclusivesTopicText.setText(_translate("MainWindow", "Exclusive addresses : "))
        self.settingsProxyExclusivesApplyButton.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Page"))
        self.sideMenuHomeButton.setText(_translate("MainWindow", "Home"))
        self.sideMenuAccountButton.setText(_translate("MainWindow", "Account"))
        self.sideMenuConfigsButton.setText(_translate("MainWindow", "My Configs"))
        self.sideMenuBuyConfigsButton.setText(_translate("MainWindow", "Buy Configs"))
        self.sideMenuSettingsButton.setText(_translate("MainWindow", "Settings"))
        self.sideMenuBuyCoinsButton.setText(_translate("MainWindow", "Buy Coins"))
