# Form implementation generated from reading ui file 'design/dotui/verify_email_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        Form.setMinimumSize(QtCore.QSize(400, 600))
        Form.setMaximumSize(QtCore.QSize(400, 600))
        Form.setStyleSheet("background-color:rgb(15, 23, 42)")
        self.headerText = QtWidgets.QLabel(parent=Form)
        self.headerText.setGeometry(QtCore.QRect(0, 70, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(36)
        self.headerText.setFont(font)
        self.headerText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.headerText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerText.setObjectName("headerText")
        self.pTextVerify = QtWidgets.QLabel(parent=Form)
        self.pTextVerify.setGeometry(QtCore.QRect(0, 130, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.pTextVerify.setFont(font)
        self.pTextVerify.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.pTextVerify.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pTextVerify.setObjectName("pTextVerify")
        self.codeEditLine = QtWidgets.QLineEdit(parent=Form)
        self.codeEditLine.setEnabled(True)
        self.codeEditLine.setGeometry(QtCore.QRect(120, 250, 161, 51))
        self.codeEditLine.setStyleSheet("QLineEdit {\n"
"    background-color: #1e293b;   /* زمینه تیره */\n"
"    color: #e2e8f0;              /* متن روشن */\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"\n"
"    /* خط و عمق */\n"
"    border: 2px solid #0f172a;\n"
"    border-bottom: 4px solid #0a0f1c;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3b82f6;   /* آبی روشن */\n"
"    border-bottom: 4px solid #2563eb;\n"
"    outline: none;\n"
"}\n"
"")
        self.codeEditLine.setMaxLength(6)
        self.codeEditLine.setFrame(True)
        self.codeEditLine.setCursorPosition(0)
        self.codeEditLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.codeEditLine.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.codeEditLine.setClearButtonEnabled(True)
        self.codeEditLine.setObjectName("codeEditLine")
        self.verifyButton = QtWidgets.QPushButton(parent=Form)
        self.verifyButton.setEnabled(True)
        self.verifyButton.setGeometry(QtCore.QRect(130, 420, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(16)
        font.setBold(True)
        self.verifyButton.setFont(font)
        self.verifyButton.setStyleSheet("#verifyButton {\n"
"    background-color: #1e293b;        /* خاکستری-آبی تیره، ست با پس‌زمینه */\n"
"    color: #e2e8f0;                   /* متن روشن (خاکستری خیلی روشن) */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    font-weight: bold;\n"
"\n"
"    /* عمق (سایه‌ی مصنوعی) */\n"
"    border: 2px solid #0f172a;        /* خط دور تیره‌تر */\n"
"    border-bottom: 4px solid #0a0f1c; /* سایه پایین برای برجسته شدن */\n"
"\n"
"    /*transition: all 0.2s;*/\n"
"}\n"
"\n"
"#verifyButton:hover {\n"
"    background-color: #334155;        /* کمی روشن‌تر وقتی موس میره روش */\n"
"    color: white;\n"
"}\n"
"\n"
"#verifyButton:pressed {\n"
"    background-color: #1e293b;\n"
"    border: 2px solid #0a0f1c;\n"
"    border-top: 4px solid #0a0f1c;    /* وقتی فشار میدی انگار دکمه فرو میره */\n"
"    padding-top: 12px;                /* حرکت جزئی برای طبیعی‌تر شدن */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.verifyButton.setObjectName("verifyButton")
        self.backToLoginButton = QtWidgets.QPushButton(parent=Form)
        self.backToLoginButton.setGeometry(QtCore.QRect(170, 477, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.backToLoginButton.setFont(font)
        self.backToLoginButton.setStyleSheet("color:white;")
        self.backToLoginButton.setIconSize(QtCore.QSize(16, 20))
        self.backToLoginButton.setFlat(True)
        self.backToLoginButton.setObjectName("backToLoginButton")
        self.arrowIcon = QtWidgets.QLabel(parent=Form)
        self.arrowIcon.setGeometry(QtCore.QRect(140, 490, 31, 16))
        self.arrowIcon.setText("")
        self.arrowIcon.setPixmap(QtGui.QPixmap(":/icons/icons/arrow-left.png"))
        self.arrowIcon.setScaledContents(True)
        self.arrowIcon.setObjectName("arrowIcon")
        self.resendCodeButton = QtWidgets.QPushButton(parent=Form)
        self.resendCodeButton.setGeometry(QtCore.QRect(140, 315, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.resendCodeButton.setFont(font)
        self.resendCodeButton.setStyleSheet("#resendCodeButton {\n"
"    background-color: #1e293b;        /* خاکستری-آبی تیره، ست با پس‌زمینه */\n"
"    color: #e2e8f0;                   /* متن روشن (خاکستری خیلی روشن) */\n"
"    border-radius: 10px;\n"
"    padding: 10px 18px;\n"
"    font-weight: bold;\n"
"\n"
"    /* عمق (سایه‌ی مصنوعی) */\n"
"    border: 2px solid #0f172a;        /* خط دور تیره‌تر */\n"
"    border-bottom: 4px solid #0a0f1c; /* سایه پایین برای برجسته شدن */\n"
"\n"
"    /*transition: all 0.2s;*/\n"
"}\n"
"\n"
"#resendCodeButton:hover {\n"
"    background-color: #334155;        /* کمی روشن‌تر وقتی موس میره روش */\n"
"    color: white;\n"
"}\n"
"\n"
"#resendCodeButton:pressed {\n"
"    background-color: #1e293b;\n"
"    border: 2px solid #0a0f1c;\n"
"    border-top: 4px solid #0a0f1c;    /* وقتی فشار میدی انگار دکمه فرو میره */\n"
"    padding-top: 12px;                /* حرکت جزئی برای طبیعی‌تر شدن */\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.resendCodeButton.setFlat(True)
        self.resendCodeButton.setObjectName("resendCodeButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.codeEditLine, self.resendCodeButton)
        Form.setTabOrder(self.resendCodeButton, self.verifyButton)
        Form.setTabOrder(self.verifyButton, self.backToLoginButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LithiumVPN - verify your email address"))
        self.headerText.setText(_translate("Form", "LithiumVPN"))
        self.pTextVerify.setText(_translate("Form", "Verify your email"))
        self.codeEditLine.setPlaceholderText(_translate("Form", "enter securety code"))
        self.verifyButton.setText(_translate("Form", "Verify"))
        self.backToLoginButton.setText(_translate("Form", "Back to login"))
        self.resendCodeButton.setText(_translate("Form", "Resend Code"))
