# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        Form.setMinimumSize(QtCore.QSize(400, 600))
        Form.setMaximumSize(QtCore.QSize(400, 600))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        Form.setFont(font)
        Form.setStyleSheet("background-color:rgb(15, 23, 42)")
        self.headerText = QtWidgets.QLabel(parent=Form)
        self.headerText.setGeometry(QtCore.QRect(0, 100, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(36)
        self.headerText.setFont(font)
        self.headerText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.headerText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerText.setObjectName("headerText")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(90, 265, 251, 41))
        self.lineEdit.setStyleSheet("background-color:rgb(249, 249, 249);\n"
"color:black;\n"
"border-radius:8")
        self.lineEdit.setMaxLength(100)
        self.lineEdit.setFrame(True)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 342, 251, 41))
        self.lineEdit_2.setStyleSheet("background-color:rgb(249, 249, 249);\n"
"color:black;\n"
"border-radius:8")
        self.lineEdit_2.setMaxLength(100)
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(50, 271, 32, 32))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/user_for_login.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(52, 347, 30, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/key.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.headerText_2 = QtWidgets.QLabel(parent=Form)
        self.headerText_2.setGeometry(QtCore.QRect(0, 160, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.headerText_2.setFont(font)
        self.headerText_2.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.headerText_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerText_2.setObjectName("headerText_2")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(130, 450, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(249, 249, 249);\n"
"color:black;\n"
"border-radius:12")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.headerText.setText(_translate("Form", "LithiumVPN"))
        self.lineEdit.setPlaceholderText(_translate("Form", "enter your email address"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "enter you password"))
        self.headerText_2.setText(_translate("Form", "Login to your account"))
        self.pushButton.setText(_translate("Form", "Login"))
