# Form implementation generated from reading ui file './ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        MainWindow.setMinimumSize(QtCore.QSize(400, 600))
        MainWindow.setMaximumSize(QtCore.QSize(400, 600))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(15, 23, 42)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, -30, 400, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.homeTab = QtWidgets.QWidget()
        self.homeTab.setObjectName("homeTab")
        self.profileIcon = QtWidgets.QLabel(parent=self.homeTab)
        self.profileIcon.setGeometry(QtCore.QRect(20, 20, 48, 48))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.profileIcon.setFont(font)
        self.profileIcon.setText("")
        self.profileIcon.setPixmap(QtGui.QPixmap(":/icons/icons/user.png"))
        self.profileIcon.setScaledContents(True)
        self.profileIcon.setObjectName("profileIcon")
        self.connectionStatusText = QtWidgets.QLabel(parent=self.homeTab)
        self.connectionStatusText.setGeometry(QtCore.QRect(110, 380, 201, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(16)
        self.connectionStatusText.setFont(font)
        self.connectionStatusText.setStyleSheet("color:rgb(148, 163, 184)")
        self.connectionStatusText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.connectionStatusText.setObjectName("connectionStatusText")
        self.headerText = QtWidgets.QLabel(parent=self.homeTab)
        self.headerText.setGeometry(QtCore.QRect(80, 20, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(28)
        self.headerText.setFont(font)
        self.headerText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.headerText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerText.setObjectName("headerText")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.homeTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 110, 65, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.coinLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.coinLayout.setContentsMargins(0, 0, 0, 0)
        self.coinLayout.setObjectName("coinLayout")
        self.coinNumber = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.coinNumber.setFont(font)
        self.coinNumber.setObjectName("coinNumber")
        self.coinLayout.addWidget(self.coinNumber)
        self.coinIcon = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.coinIcon.setEnabled(False)
        self.coinIcon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/coin.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/coin.png"), QtGui.QIcon.Mode.Disabled, QtGui.QIcon.State.Off)
        self.coinIcon.setIcon(icon)
        self.coinIcon.setCheckable(False)
        self.coinIcon.setFlat(True)
        self.coinIcon.setObjectName("coinIcon")
        self.coinLayout.addWidget(self.coinIcon)
        self.usernameText = QtWidgets.QLabel(parent=self.homeTab)
        self.usernameText.setGeometry(QtCore.QRect(30, 70, 81, 39))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.usernameText.setFont(font)
        self.usernameText.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.usernameText.setObjectName("usernameText")
        self.selectConfigComboBox = QtWidgets.QComboBox(parent=self.homeTab)
        self.selectConfigComboBox.setGeometry(QtCore.QRect(110, 430, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.selectConfigComboBox.setFont(font)
        self.selectConfigComboBox.setStyleSheet("QScrollBar:vertical {\n"
"    background: #f0f0f0;   /* پس زمینه */\n"
"    width: 10px;           /* ضخامت اسکرول بار */\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #888;      /* رنگ دستگیره (قابل حرکت) */\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #555;      /* رنگ دستگیره وقتی موس روشه */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;      /* دکمه‌های بالا/پایین رو حذف میکنه */\n"
"}\n"
"")
        self.selectConfigComboBox.setMaxVisibleItems(3)
        self.selectConfigComboBox.setObjectName("selectConfigComboBox")
        self.selectConfigComboBox.addItem("")
        self.selectConfigComboBox.addItem("")
        self.selectConfigComboBox.addItem("")
        self.selectConfigComboBox.addItem("")
        self.selectConfigComboBox.addItem("")
        self.continueProfileLine = QtWidgets.QFrame(parent=self.homeTab)
        self.continueProfileLine.setGeometry(QtCore.QRect(10, 70, 20, 71))
        self.continueProfileLine.setStyleSheet("color:rgb(230, 230, 230)")
        self.continueProfileLine.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.continueProfileLine.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.continueProfileLine.setLineWidth(2)
        self.continueProfileLine.setObjectName("continueProfileLine")
        self.menuButton = QtWidgets.QPushButton(parent=self.homeTab)
        self.menuButton.setGeometry(QtCore.QRect(330, 20, 51, 51))
        self.menuButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuButton.setIcon(icon1)
        self.menuButton.setIconSize(QtCore.QSize(30, 48))
        self.menuButton.setFlat(True)
        self.menuButton.setObjectName("menuButton")
        self.powerButtonBase = QtWidgets.QPushButton(parent=self.homeTab)
        self.powerButtonBase.setGeometry(QtCore.QRect(105, 145, 210, 210))
        self.powerButtonBase.setStyleSheet("border-radius : 100; \n"
"background-color: white")
        self.powerButtonBase.setText("")
        self.powerButtonBase.setIconSize(QtCore.QSize(110, 110))
        self.powerButtonBase.setObjectName("powerButtonBase")
        self.powerButton = QtWidgets.QPushButton(parent=self.homeTab)
        self.powerButton.setGeometry(QtCore.QRect(110, 150, 200, 200))
        self.powerButton.setStyleSheet("border-radius : 100; \n"
"background-color: qlineargradient(spread:pad, x1:0.462, y1:0, x2:0.473, y2:1, stop:0 rgba(107, 114, 128, 255), stop:1 rgba(210, 220, 236, 255))")
        self.powerButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/power.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.powerButton.setIcon(icon2)
        self.powerButton.setIconSize(QtCore.QSize(150, 150))
        self.powerButton.setObjectName("powerButton")
        self.tabWidget.addTab(self.homeTab, "")
        self.accountTab = QtWidgets.QWidget()
        self.accountTab.setObjectName("accountTab")
        self.tabWidget.addTab(self.accountTab, "")
        self.configsTab = QtWidgets.QWidget()
        self.configsTab.setObjectName("configsTab")
        self.tabWidget.addTab(self.configsTab, "")
        self.buyConfigsTab = QtWidgets.QWidget()
        self.buyConfigsTab.setObjectName("buyConfigsTab")
        self.tabWidget.addTab(self.buyConfigsTab, "")
        self.settingsTab = QtWidgets.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.tabWidget.addTab(self.settingsTab, "")
        self.sideMenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.sideMenu.setGeometry(QtCore.QRect(400, 20, 111, 341))
        self.sideMenu.setStyleSheet("/*background-color: rgb(30, 41, 59);*/\n"
"\n"
"\n"
"#sideMenu {\n"
"    background-color: rgb(30, 41, 59); /* پس‌زمینه منو */\n"
"    border-radius:14px;\n"
"}\n"
"\n"
"#sideMenu QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(241, 245, 249);\n"
"    padding: 8px 16px;\n"
"    text-align: left;\n"
"    border: none;\n"
"}\n"
"\n"
"#sideMenu QPushButton:hover {\n"
"    background-color: rgb(51, 65, 85);\n"
"}\n"
"\n"
"#sideMenu QPushButton:checked {\n"
"    background-color: rgb(59, 130, 246); /* آبی برای آیتم انتخاب‌شده */\n"
"    color: white;\n"
"}")
        self.sideMenu.setObjectName("sideMenu")
        self.sideMenuHomeButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuHomeButton.setGeometry(QtCore.QRect(0, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuHomeButton.setFont(font)
        self.sideMenuHomeButton.setObjectName("sideMenuHomeButton")
        self.sideMenuAccountButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuAccountButton.setGeometry(QtCore.QRect(0, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuAccountButton.setFont(font)
        self.sideMenuAccountButton.setObjectName("sideMenuAccountButton")
        self.sideMenuConfigsButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuConfigsButton.setGeometry(QtCore.QRect(0, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuConfigsButton.setFont(font)
        self.sideMenuConfigsButton.setObjectName("sideMenuConfigsButton")
        self.sideMenuBuyConfigsButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuBuyConfigsButton.setGeometry(QtCore.QRect(0, 180, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuBuyConfigsButton.setFont(font)
        self.sideMenuBuyConfigsButton.setObjectName("sideMenuBuyConfigsButton")
        self.sideMenuSettingsButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuSettingsButton.setGeometry(QtCore.QRect(0, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuSettingsButton.setFont(font)
        self.sideMenuSettingsButton.setObjectName("sideMenuSettingsButton")
        self.sideMenuBuyCoinsButton = QtWidgets.QPushButton(parent=self.sideMenu)
        self.sideMenuBuyCoinsButton.setGeometry(QtCore.QRect(0, 230, 111, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        self.sideMenuBuyCoinsButton.setFont(font)
        self.sideMenuBuyCoinsButton.setObjectName("sideMenuBuyCoinsButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LithiumVPN"))
        self.connectionStatusText.setText(_translate("MainWindow", "Not Connected"))
        self.headerText.setText(_translate("MainWindow", "LithiumVPN"))
        self.coinNumber.setText(_translate("MainWindow", "160"))
        self.usernameText.setText(_translate("MainWindow", "Username"))
        self.selectConfigComboBox.setPlaceholderText(_translate("MainWindow", "select config"))
        self.selectConfigComboBox.setItemText(0, _translate("MainWindow", "item1"))
        self.selectConfigComboBox.setItemText(1, _translate("MainWindow", "item2"))
        self.selectConfigComboBox.setItemText(2, _translate("MainWindow", "item3"))
        self.selectConfigComboBox.setItemText(3, _translate("MainWindow", "item4"))
        self.selectConfigComboBox.setItemText(4, _translate("MainWindow", "item5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.homeTab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.accountTab), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configsTab), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buyConfigsTab), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), _translate("MainWindow", "Page"))
        self.sideMenuHomeButton.setText(_translate("MainWindow", "Home"))
        self.sideMenuAccountButton.setText(_translate("MainWindow", "Account"))
        self.sideMenuConfigsButton.setText(_translate("MainWindow", "Configs"))
        self.sideMenuBuyConfigsButton.setText(_translate("MainWindow", "Buy Configs"))
        self.sideMenuSettingsButton.setText(_translate("MainWindow", "Settings"))
        self.sideMenuBuyCoinsButton.setText(_translate("MainWindow", "Buy Coins"))
