# Form implementation generated from reading ui file 'verify_email_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        Form.setMinimumSize(QtCore.QSize(400, 600))
        Form.setMaximumSize(QtCore.QSize(400, 600))
        Form.setStyleSheet("background-color:rgb(15, 23, 42)")
        self.headerText = QtWidgets.QLabel(parent=Form)
        self.headerText.setGeometry(QtCore.QRect(0, 130, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(36)
        self.headerText.setFont(font)
        self.headerText.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.headerText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.headerText.setObjectName("headerText")
        self.pTextVerify = QtWidgets.QLabel(parent=Form)
        self.pTextVerify.setGeometry(QtCore.QRect(0, 190, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(12)
        self.pTextVerify.setFont(font)
        self.pTextVerify.setStyleSheet("color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.488636, y2:0, stop:0 rgba(59, 130, 246, 255), stop:1 rgba(6, 182, 212, 255))")
        self.pTextVerify.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pTextVerify.setObjectName("pTextVerify")
        self.codeEditLine = QtWidgets.QLineEdit(parent=Form)
        self.codeEditLine.setGeometry(QtCore.QRect(130, 290, 141, 41))
        self.codeEditLine.setStyleSheet("background-color:rgb(249, 249, 249);\n"
"color:black;\n"
"border-radius:8")
        self.codeEditLine.setMaxLength(6)
        self.codeEditLine.setFrame(True)
        self.codeEditLine.setCursorPosition(0)
        self.codeEditLine.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.codeEditLine.setClearButtonEnabled(True)
        self.codeEditLine.setObjectName("codeEditLine")
        self.verifyButton = QtWidgets.QPushButton(parent=Form)
        self.verifyButton.setGeometry(QtCore.QRect(130, 388, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(16)
        self.verifyButton.setFont(font)
        self.verifyButton.setStyleSheet("background-color:rgb(249, 249, 249);\n"
"color:black;\n"
"border-radius:12")
        self.verifyButton.setObjectName("verifyButton")
        self.backToLoginButton = QtWidgets.QPushButton(parent=Form)
        self.backToLoginButton.setGeometry(QtCore.QRect(160, 511, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.backToLoginButton.setFont(font)
        self.backToLoginButton.setIconSize(QtCore.QSize(16, 20))
        self.backToLoginButton.setFlat(True)
        self.backToLoginButton.setObjectName("backToLoginButton")
        self.arrowIcon = QtWidgets.QLabel(parent=Form)
        self.arrowIcon.setGeometry(QtCore.QRect(144, 524, 16, 16))
        self.arrowIcon.setText("")
        self.arrowIcon.setPixmap(QtGui.QPixmap(":/icons/icons/arrow-left.png"))
        self.arrowIcon.setScaledContents(True)
        self.arrowIcon.setObjectName("arrowIcon")
        self.resendCodeButton = QtWidgets.QPushButton(parent=Form)
        self.resendCodeButton.setGeometry(QtCore.QRect(140, 463, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.resendCodeButton.setFont(font)
        self.resendCodeButton.setFlat(True)
        self.resendCodeButton.setObjectName("resendCodeButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LithiumVPN - verify your email address"))
        self.headerText.setText(_translate("Form", "LithiumVPN"))
        self.pTextVerify.setText(_translate("Form", "Verify your email"))
        self.codeEditLine.setPlaceholderText(_translate("Form", "enter securety code"))
        self.verifyButton.setText(_translate("Form", "Verify"))
        self.backToLoginButton.setText(_translate("Form", "Back to login"))
        self.resendCodeButton.setText(_translate("Form", "Resend Code"))
